### ISSUE TITLE
Creazione e stesura delle Views secondarie

### ISSUE THREAD

**Issue by MaurizioLeombruni** [MaurizioLeombruni/agenzia-viaggio-mvc#2]
Qualcuno si occuperà di fare le views secondarie (Dettagli, Creare, Modificare).

- [x] Dettagli del viaggio selezionato

- [x] Creare un viaggio con un form

- [x] Modificare un viaggio già esistente

**Comment by lucianocecere07** [comment]
Modificata visualizzazione della Issue per prova di GitHub

**Comment by lucianocecere07** [comment]
close issue
